### ISSUE TITLE
[BUG] ReferenceDiscoveryService.Discover breaks on NTFS junction points

### ISSUE THREAD

**Issue by mercenaryntx** [madushans/DependenSee#20]
Hey there,

Our .NET source code repository contains some front-end codes as well coming with pnpm package management which tends to use NTFS junction points to avoid node_modules folders. This causes the DependenSee discovery to fail when it hits a junction point.

```
Directory of $SOURCE\node_modules\.pnpm\@vue+compiler-core@3.2.20\node_modules\@babel

2022-04-01  09:11 AM    <DIR>          .
2022-04-01  09:11 AM    <DIR>          ..
2022-04-01  09:11 AM    <JUNCTION>     parser [$SOURCE\node_modules\.pnpm\@babel+parser@7.17.8\node_modules\@babel\parser]
               0 File(s)              0 bytes
```

**DependenSee Command**
`DependenSee . -P -O outputPath`

**DependenSee Output**
```
System.IO.DirectoryNotFoundException:Could not find a part of the path '$SOURCE\node_modules\.pnpm\@vue+compiler-core@3.2.20\node_modules\@babel\parser'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at DependenSee.ReferenceDiscoveryService.Discover(String folder, DiscoveryResult result) in D:\a\1\s\DependenSee\ReferenceDiscoveryService.cs:line 61
   at DependenSee.ReferenceDiscoveryService.Discover(String folder, DiscoveryResult result) in D:\a\1\s\DependenSee\ReferenceDiscoveryService.cs:line 119
   at DependenSee.ReferenceDiscoveryService.Discover(String folder, DiscoveryResult result) in D:\a\1\s\DependenSee\ReferenceDiscoveryService.cs:line 119
   at DependenSee.ReferenceDiscoveryService.Discover(String folder, DiscoveryResult result) in D:\a\1\s\DependenSee\ReferenceDiscoveryService.cs:line 119
   at DependenSee.ReferenceDiscoveryService.Discover(String folder, DiscoveryResult result) in D:\a\1\s\DependenSee\ReferenceDiscoveryService.cs:line 119
   at DependenSee.ReferenceDiscoveryService.Discover(String folder, DiscoveryResult result) in D:\a\1\s\DependenSee\ReferenceDiscoveryService.cs:line 119
   at DependenSee.ReferenceDiscoveryService.Discover(String folder, DiscoveryResult result) in D:\a\1\s\DependenSee\ReferenceDiscoveryService.cs:line 119
   at DependenSee.ReferenceDiscoveryService.Discover() in D:\a\1\s\DependenSee\ReferenceDiscoveryService.cs:line 48
   at DependenSee.PowerArgsProgram.Main() in D:\a\1\s\DependenSee\PowerArgsProgram.cs:line 91
--- End of stack trace from previous location ---
   at PowerArgs.ObjectEx.InvokeMainMethod(Object o)
   at PowerArgs.Args.<>c__DisplayClass15_1.<InvokeMain>b__1()
   at PowerArgs.Args.Execute[T](Func`1 argsProcessingCode)
   at PowerArgs.Args.<>c__DisplayClass15_0.<InvokeMain>b__0(String[] a)
   at PowerArgs.REPL.DriveREPL[T](TabCompletion t, Func`2 eval, String[] args, Func`1 defaultEval)
   at PowerArgs.Args.InvokeMain(CommandLineArgumentsDefinition definition, String[] args)
   at PowerArgs.Args.InvokeMain[T](String[] args)
   at DependenSee.Program.Main(String[] args) in D:\a\1\s\DependenSee\Program.cs:line 19
```

**DependenSee Version**
2.1.0

**Comment by madushans** [comment]
2.2.0 fixes this by skipping non existent folder references, and reparse points.
New flag `-FollowReparsePoints` is available if you like to traverse them.

If you have reparse points that you'd like to traverse, but also reparse points like above you'd like to avoid, you can set `-FollowReparsePoints` but also use the new `-ExcludeFolders` to exclude a set of folders from scanning.

https://github.com/madushans/DependenSee/releases/tag/2.2.0
